shvedovaav/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.StoreHome.as_view(), name='home'),
    path('accord', views.StoreAccord.as_view(), name='accord'),
    path('denial', views.StoreDenial.as_view(), name='denial'),
    path('confidence', views.StoreConfidence.as_view(), name='confidence'),
    path('terms_of_use', views.StoreTermOfUse.as_view(), name='terms_of_use'),
    path('placing_an_order/<int:id>/', views.StorePlacingAnOrder.as_view(), name='placing_an_order'),
    path('product/<int:id>/', views.StoreProduct.as_view(), name='product'),
    path('thank_you/', views.StoreThankYou.as_view(), name='thank_you'),
    path('payment_result/', views.payment_result, name='payment_result'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    
    path('password-reset/', views.UserPasswordReset.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def image_path(instance, filename):
        return '/'.join(['users', str(instance.id), filename])

    photo = models.ImageField(upload_to=image_path, blank=True, null=True, verbose_name="Фотография")
    phone = models.CharField(max_length=15, blank=True, null=True, verbose_name="Номер телефона")
    is_accepted = models.BooleanField(verbose_name="Согласие на обработку персональных данных", null=True)

    

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model, password_validation


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Эл. адрес', widget=forms.EmailInput(attrs={'class': 'form-item__text'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Эл. адрес', 
        widget=forms.EmailInput(attrs={'class': 'form-item__text'}),
        error_messages={'unique': 'Такой e-mail уже зарегистрирован.'}
        )
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))
    password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))
    is_accepted = forms.BooleanField(initial=False, label="Согласие на обработку персональных данных", widget=forms.CheckboxInput(attrs={'class': 'form-item__text'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'first_name', 'is_accepted']
        labels ={
            'first_name': 'Ваше имя',
            'phone': 'Номер телефона',
        }
        widgets ={
            'first_name': forms.TextInput(attrs={'class': 'form-item__text'}),
            # 'phone': forms.TextInput(attrs={'class': 'form-item__text'}),
        }

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        disabled=True, 
        label='Эл. адрес', 
        widget=forms.EmailInput(attrs={'class': 'form-item__text'})
        )
    first_name = forms.CharField(
        label='Ваше имя', 
        widget=forms.TextInput(attrs={'class': 'form-item__text'}),
        )
    phone = forms.CharField(
        label='Номер телефона', 
        widget=forms.TextInput(attrs={'class': 'form-item__text'}),
        )
    photo = forms.ImageField(
        label='Фотография', 
        widget=forms.FileInput(attrs={'class': 'form-item__text'}),
        )

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'phone', 'photo']
        labels ={
            'first_name': 'Ваше имя',
        }
        widgets ={
            'first_name': forms.TextInput(attrs={'class': 'form-item__text'}),
            'phone': forms.TextInput(attrs={'class': 'form-item__text'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))
    new_password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput(attrs={'class': 'form-item__text'}))

class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label='Эл. адрес', widget=forms.EmailInput(attrs={'class': 'form-item__text'}))     
  
class UserPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=("Новый пароль"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-item__text'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=("Подтвердите новый пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-item__text'}),
    )
    
   

users/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetConfirmView, PasswordResetView
from django.views.generic import CreateView, UpdateView
from store.utils import DataMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm, UserPasswordResetForm, UserPasswordResetConfirmForm
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    title = "Авторизация"


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    title = "Регистрация"
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        title_message = 'Регистрация'
        text_message = f"""{form.cleaned_data['first_name']}, Вы зарегистрировались на сайте shvedovaav.ru!"""
        email_to = [form.cleaned_data['username']]

        email = EmailMessage(
            subject=title_message,
            body=text_message,
        to=email_to
        )
        email.send()
        return super().form_valid(form)


class ProfileUser(LoginRequiredMixin, DataMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    title = "Профиль пользователя"

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(LoginRequiredMixin, DataMixin, PasswordChangeView):
    form_class =  UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'
    title = 'Смена пароля'


class UserPasswordReset(DataMixin, PasswordResetView):
    form_class = UserPasswordResetForm
    template_name='users/password_reset_form.html'
    email_template_name='users/password_reset_email.html'
    success_url=reverse_lazy('users:password_reset_done')
    title = "Сброс пароля"


class UserPasswordResetConfirm(DataMixin, PasswordResetConfirmView):
    form_class = UserPasswordResetConfirmForm
    template_name='users/password_reset_confirm.html'
    success_url=reverse_lazy('users:password_reset_complete')
    title = "Новый пароль"

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %} Логин {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Вход</div>
        <div class="form__body">
            <form method="post">
                {% csrf_token %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}

                <div class="form__item">
                    <input class="btn__input" type="submit" value="Войти" />
                </div>
            </form>
            <a href="{% url 'users:password_reset' %}" class="btn__link">Забыли пароль?</a>

        </div>
    </div>

</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="description">
    <div class="container">
        <div class="description__body">
            <div class="description__title title">Ваш пароль успешно изменен</div>
            <a href="{% url 'users:profile' %}" class="btn__link">Вернуться в профиль</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Изменение пароля</div>
        <div class="form__body">
            <form method="post">
                {% csrf_token %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}

                <div class="form__item">
                    <input class="btn__input" type="submit" value="Изменить" />
                </div>
            </form>
            

        </div>
    </div>

</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}

<div class="description">
    <div class="container">
        <div class="description__body">
            <div class="description__title title">Пароль изменен</div>
            <div class="description-header__text">
                Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
                <a href="{% url 'users:profile' %}" class="btn__link">входа в систему.</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Новый пароль</div>
        <div class="form__body">
            <form method="post">
                {% csrf_token %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}
                <div class="form__item">
                    <input class="btn__input" type="submit" value="Сохранить" />
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="description">
    <div class="container">
        <div class="description__body">
            <div class="description__title title">Сброс пароля</div>
            {% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}
            {% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}
            <a href="{% url 'users:profile' %}" class="btn__link">Вернуться в профиль</a>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %} 
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktranslate %} 
{% translate "Please go to the following page and choose a new password:" %} 
{% block reset_link %} {{ protocol }}://{{ domain }}
{% url 'users:password_reset_confirm' uidb64=uid token=token %} 
{% endblock %} 
{% translate 'Your username, in case you’ve forgotten:' %} 
{{ user.get_username }} 
{% translate "Thanks for using our site!" %} 
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %} 
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Восстановление пароля</div>
        <div class="form__body">
            <form method="post">
                {% csrf_token %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}
                <div class="form__item">
                    <input class="btn__input" type="submit" value="Восстановить" />
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Редактировать</div>
        <div class="form__body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if user.photo %}
                <p><img src="{{ user.photo.url }}" width="200" height="200"></p>
                {% else %}
                <p><img src="{% static 'users/default_user_photo.png' %}" width="200" height="200"></p>
                {% endif %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}

                <div class="form__item">
                    <input class="btn__input" type="submit" value="Сохранить" />
                </div>
            </form>
            <br>
            <a href="{% url 'users:password_change' %}" class="btn__link">Сменить пароль</a>

        </div>
    </div>

</div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="form">
    <div class="container">
        <div class="form__title">Регистрация</div>
        <div class="form__body">
            <form method="post">
                {% csrf_token %}
                <div class="form__item">{{ form.non_field_errors}}</div>
                {% for field in form %}
                <div class="form__item">
                    {{ field.label }}<br />
                    {{ field }} {{field.errors}}
                </div>
                {% endfor %}
                <p> Я принимаю условия <a href="{% url 'terms_of_use' %}">Пользовательского соглашения</a> 
                    и даю свое согласие АШАШ на обработку моей персональной
                информации на условиях, опреденных <a href="{% url 'confidence' %}">Политикой конфиденциальности</a> </p>
                <div class="form__item">
                    <input class="btn__input" type="submit" value="Зарегистрироваться" />
                </div>
            </form>

        </div>
    </div>

</div>
{% endblock %}