shvedovaav/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.StoreHome.as_view(), name='home'),
    path('accord', views.StoreAccord.as_view(), name='accord'),
    path('denial', views.StoreDenial.as_view(), name='denial'),
    path('confidence', views.StoreConfidence.as_view(), name='confidence'),
    path('terms_of_use', views.StoreTermOfUse.as_view(), name='terms_of_use'),
    path('placing_an_order/<int:id>/', views.StorePlacingAnOrder.as_view(), name='placing_an_order'),
    path('product/<int:id>/', views.StoreProduct.as_view(), name='product'),
    path('thank_you/', views.StoreThankYou.as_view(), name='thank_you'),
    path('payment_result/', views.payment_result, name='payment_result'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    
    path('password-reset/', views.UserPasswordReset.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'store/images/icons/icon.png' %}" type="image/png" />
    <script src="{% static 'store/jquery/jquery-3.6.0.min.js' %}"></script>

    <script src="{% static 'store/jquery/jquery.validate.min.js' %}"></script>
    <script src="{% static 'store/jquery/jquery.validate.unobtrusive.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'store/bootstrap_svg/bootstrap-icons.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/swipe/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/style.css' %}" />
    <script src="{% static 'store/swipe/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'store/js/style.js' %}"></script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    <div class="wrapper">
        <div class="header">
            <div class="container">
                <div class="header__body">
                    <div class="header__burger">
                        <span></span>
                    </div>
                    <div class="header__menu">
                        <ul class="header__list">
                            <li><a class="header__link" href="/">АШАШ</a></li>
                            <li><a class="header__link" href="/#courses">КУРСЫ</a></li>
                            <li><a class="header__link" href="/#feedbacks">ОТЗЫВЫ</a></li>
                            <li><a class="header__link" href="/#about">О НАС</a></li>
                        </ul>
                    </div>
                    <div class="header__phone"><img src="{% static 'store/images/icons/phone.png' %}"
                            alt="">8-909-65-258-65</div>
                    <div class="header__btn">
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}" class="btn__link">{{ user.first_name }}</a><span class="btn__link_span">|</span>
                        <a href="{% url 'users:logout' %}" class="btn__link">Выйти</a>
                        {% else %}
                        <a href="{% url 'users:login' %}" class="btn__link">Войти</a><span class="btn__link_span">|</span>
                        <a href="{% url 'users:register' %}" class="btn__link">Регистрация</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <div class="container">
                <!-- Блок согласие на обработку данных -->

                <!-- <div class="cookie">
                                <div class="cookie__body">
                                    <div class="cookie__text">
                                            На сайте используется сбор данных Cookies. 
                                            Чтобы ознакомиться пройдите по ссылке <a href="~/Home/Confidence">Политика конфиденциальности</a>. 
                                            Согласие на сбор данных <a asp-action="cookiesAccept" asp-controller="home" class="cookie__link">Принять</a>
                                    </div>
                                </div>
                            </div> -->
                <div class="footer__body">
                    <div class="footer__row">
                        <div class="footer__column">
                            <a href="https://t.me/shvedovaanna" target="_blank"><img
                                    src="{% static 'store/images/icons/telegram.png' %}" alt=""></a>
                            <a href="https://www.youtube.com/c/АвторскаяШколаАнныШведовой" target="_blank"><img
                                    src="{% static 'store/images/icons/youtube.png' %}" alt=""></a>
                            <p>АШАШ © {{ year }}</p>
                        </div>

                        <div class="footer__column">
                            <ul>
                                <li>Контакты</li>
                                <li>8-909-65-258-65</li>
                                <li>info@shvedovaav.ru</li>
                            </ul>
                        </div>
                        <div class="footer__column">
                            <ul>
                                <li><a href="/accord">Согласие с рассылкой</a></li>
                                <li><a href="/confidence">Политика конфиденциальности</a></li>
                                <li><a href="/denial">Отказ от ответсвенности</a></li>
                                <li><a href="/terms_of_use">Пользовательское соглашение</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>

</html>